---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos
  driver_config:
    image: "centos"
    platform: "rhel"
  run_list:
  - recipe[yum]

suites:
- name: default
  run_list: ["recipe[s3cmd]"]
  attributes:
    s3cmd:
      access_key: attr_access
      secret_key: attr_secret
