---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.4
  driver_config:
    box: cent6.4

suites:
- name: default
  run_list: ["recipe[s3cmd]"]
  attributes:
    s3cmd:
      access_key: attr_access
      secret_key: attr_secret
